[2022-07-07 07:47:45] [[31merror[39m] FUNC: event transfer 
[2022-07-07 07:49:43] [[31merror[39m] FUNC: event transfer 
[2022-07-07 08:12:57] [[31merror[39m] Error: Key derivation failed - possibly wrong password
    at Accounts.decrypt (/home/trongnm/Documents/apieth/node_modules/web3-eth-accounts/lib/index.js:438:15)
    at create (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:22:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 08:14:03] [[31merror[39m] Error: Key derivation failed - possibly wrong password
    at Accounts.decrypt (/home/trongnm/Documents/apieth/node_modules/web3-eth-accounts/lib/index.js:438:15)
    at create (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:22:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 09:47:25] [[31merror[39m] TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at Accounts.encrypt (/home/trongnm/Documents/apieth/node_modules/web3-eth-accounts/lib/index.js:466:47)
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:90:48)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 09:47:49] [[31merror[39m] TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at Accounts.encrypt (/home/trongnm/Documents/apieth/node_modules/web3-eth-accounts/lib/index.js:466:47)
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:90:48)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:15:54] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:20:45] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:23:16] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:23:52] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:25:44] [[31merror[39m] TypeError: Cannot read property 'msg' of undefined
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:53)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:26:05] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:26:24] [[31merror[39m] register: Error: Missing where attribute in the options parameter passed to findOrCreate. Please note that the API has changed, and is now options only (an object with where, defaults keys, transaction etc.)
[2022-07-07 10:26:24] [[31merror[39m] Error: Missing where attribute in the options parameter passed to findOrCreate. Please note that the API has changed, and is now options only (an object with where, defaults keys, transaction etc.)
    at Function.findOrCreate (/home/trongnm/Documents/apieth/node_modules/sequelize/lib/model.js:1370:13)
    at Object.register (/home/trongnm/Documents/apieth/app/services/authServices.js:19:24)
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:89:47)
[2022-07-07 10:50:20] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:51:10] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:53:19] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:53:55] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:55:07] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:55:25] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 10:57:52] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:04:44] [[31merror[39m] register: Error: Missing where attribute in the options parameter passed to findOrCreate. Please note that the API has changed, and is now options only (an object with where, defaults keys, transaction etc.)
[2022-07-07 11:04:44] [[31merror[39m] Error: Missing where attribute in the options parameter passed to findOrCreate. Please note that the API has changed, and is now options only (an object with where, defaults keys, transaction etc.)
    at Function.findOrCreate (/home/trongnm/Documents/apieth/node_modules/sequelize/lib/model.js:1370:13)
    at Object.register (/home/trongnm/Documents/apieth/app/services/authServices.js:19:24)
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:89:47)
[2022-07-07 11:08:21] [[31merror[39m] TypeError: Cannot read property 'result' of undefined
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:45:67)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:08:58] [[31merror[39m] TypeError: Cannot read property 'result' of undefined
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:45:67)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:11:11] [[31merror[39m] TypeError: Cannot read property 'password' of undefined
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:45:74)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:11:34] [[31merror[39m] TypeError: Cannot read property 'password' of undefined
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:46:74)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:20:00] [[31merror[39m] TypeError: Cannot read property 'password' of undefined
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:46:74)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:20:30] [[31merror[39m] TypeError: Cannot read property 'email' of undefined
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:48:76)
[2022-07-07 11:20:53] [[31merror[39m] TypeError: Cannot read property 'id' of undefined
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:48:101)
[2022-07-07 11:21:06] [[31merror[39m] TypeError: Cannot read property 'passwordWallet' of undefined
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:52:53)
[2022-07-07 11:21:37] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:37:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:22:14] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:37:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:22:24] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:73:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:22:25] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:73:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:22:25] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:73:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:22:26] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:73:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:22:29] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:73:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:22:36] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:73:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:23:47] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:37:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:24:25] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:37:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:24:26] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:37:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:24:27] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:37:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:45:01] [[31merror[39m] ReferenceError: validationResult is not defined
    at create (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:15:28)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:45:54] [[31merror[39m] TypeError: Cannot read property 'keystore' of undefined
    at create (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:29:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:46:11] [[31merror[39m] ReferenceError: retry is not defined
    at create (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:32:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:49:32] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at create (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:18:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:49:34] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at create (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:18:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 11:49:34] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at create (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:18:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 13:49:16] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 13:51:28] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 13:52:07] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 13:52:25] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 13:52:26] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 13:52:49] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 13:52:51] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 13:54:06] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 13:56:34] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 14:07:08] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:66:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 14:30:06] [[31merror[39m] TypeError: Cannot read property 'keystore' of undefined
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:103:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 14:30:42] [[31merror[39m] TypeError: Cannot read property 'keystore' of undefined
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:103:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 14:31:12] [[31merror[39m] Error: Key derivation failed - possibly wrong password
    at Accounts.decrypt (/home/trongnm/Documents/apieth/node_modules/web3-eth-accounts/lib/index.js:438:15)
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:104:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 14:31:59] [[31merror[39m] transfer token: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1e+36, code=NUMERIC_FAULT, version=bignumber/5.6.2)
[2022-07-07 14:31:59] [[31merror[39m] Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1e+36, code=NUMERIC_FAULT, version=bignumber/5.6.2)
    at Logger.makeError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at throwFault (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
    at Function.BigNumber.from (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:206:17)
    at NumberCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/number.js:36:39)
    at /home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/abi-coder.js:91:15)
    at ABICoder.encodeParameters (/home/trongnm/Documents/apieth/node_modules/web3-eth-abi/lib/index.js:127:27)
    at /home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:462:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:461:8)
    at Object.transfer (/home/trongnm/Documents/apieth/app/services/tokenServices.js:36:73)
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:111:48)
[2022-07-07 14:32:22] [[31merror[39m] transfer token: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.2)
[2022-07-07 14:32:22] [[31merror[39m] Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.2)
    at Logger.makeError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at throwFault (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
    at Function.BigNumber.from (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:206:17)
    at NumberCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/number.js:36:39)
    at /home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/abi-coder.js:91:15)
    at ABICoder.encodeParameters (/home/trongnm/Documents/apieth/node_modules/web3-eth-abi/lib/index.js:127:27)
    at /home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:462:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:461:8)
    at Object.transfer (/home/trongnm/Documents/apieth/app/services/tokenServices.js:36:73)
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:111:48)
[2022-07-07 14:32:45] [[31merror[39m] transfer token: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.2)
[2022-07-07 14:32:45] [[31merror[39m] Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.2)
    at Logger.makeError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at throwFault (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
    at Function.BigNumber.from (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:206:17)
    at NumberCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/number.js:36:39)
    at /home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/abi-coder.js:91:15)
    at ABICoder.encodeParameters (/home/trongnm/Documents/apieth/node_modules/web3-eth-abi/lib/index.js:127:27)
    at /home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:462:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:461:8)
    at Object.transfer (/home/trongnm/Documents/apieth/app/services/tokenServices.js:36:73)
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:111:48)
[2022-07-07 14:33:30] [[31merror[39m] transfer token: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.2)
[2022-07-07 14:33:30] [[31merror[39m] Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.2)
    at Logger.makeError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at throwFault (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
    at Function.BigNumber.from (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:206:17)
    at NumberCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/number.js:36:39)
    at /home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/abi-coder.js:91:15)
    at ABICoder.encodeParameters (/home/trongnm/Documents/apieth/node_modules/web3-eth-abi/lib/index.js:127:27)
    at /home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:462:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:461:8)
    at Object.transfer (/home/trongnm/Documents/apieth/app/services/tokenServices.js:37:73)
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:111:48)
[2022-07-07 14:37:27] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/trongnm/Documents/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/trongnm/Documents/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/trongnm/Documents/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-07 14:37:28] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/trongnm/Documents/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/trongnm/Documents/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/trongnm/Documents/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-07 14:37:29] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/trongnm/Documents/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/trongnm/Documents/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/trongnm/Documents/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-07 14:37:29] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/trongnm/Documents/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/trongnm/Documents/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/trongnm/Documents/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-07 14:37:30] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/trongnm/Documents/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/trongnm/Documents/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/trongnm/Documents/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/trongnm/Documents/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-07 14:45:03] [[31merror[39m] transfer token: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.2)
[2022-07-07 14:45:03] [[31merror[39m] Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.2)
    at Logger.makeError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at throwFault (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
    at Function.BigNumber.from (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:206:17)
    at NumberCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/number.js:36:39)
    at /home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/abi-coder.js:91:15)
    at ABICoder.encodeParameters (/home/trongnm/Documents/apieth/node_modules/web3-eth-abi/lib/index.js:127:27)
    at /home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:462:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:461:8)
    at Object.transfer (/home/trongnm/Documents/apieth/app/services/tokenServices.js:37:73)
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:111:48)
[2022-07-07 14:48:39] [[31merror[39m] transfer token: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1e+36, code=NUMERIC_FAULT, version=bignumber/5.6.2)
[2022-07-07 14:48:39] [[31merror[39m] Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1e+36, code=NUMERIC_FAULT, version=bignumber/5.6.2)
    at Logger.makeError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at throwFault (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
    at Function.BigNumber.from (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:206:17)
    at NumberCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/number.js:36:39)
    at /home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/abi-coder.js:91:15)
    at ABICoder.encodeParameters (/home/trongnm/Documents/apieth/node_modules/web3-eth-abi/lib/index.js:127:27)
    at /home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:462:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:461:8)
    at Object.transfer (/home/trongnm/Documents/apieth/app/services/tokenServices.js:37:73)
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:111:48)
[2022-07-07 14:48:39] [[31merror[39m] transfer token: Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1e+36, code=NUMERIC_FAULT, version=bignumber/5.6.2)
[2022-07-07 14:48:39] [[31merror[39m] Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1e+36, code=NUMERIC_FAULT, version=bignumber/5.6.2)
    at Logger.makeError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:233:21)
    at Logger.throwError (/home/trongnm/Documents/apieth/node_modules/@ethersproject/logger/lib/index.js:242:20)
    at throwFault (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:303:19)
    at Function.BigNumber.from (/home/trongnm/Documents/apieth/node_modules/@ethersproject/bignumber/lib/bignumber.js:206:17)
    at NumberCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/number.js:36:39)
    at /home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/home/trongnm/Documents/apieth/node_modules/@ethersproject/abi/lib/abi-coder.js:91:15)
    at ABICoder.encodeParameters (/home/trongnm/Documents/apieth/node_modules/web3-eth-abi/lib/index.js:127:27)
    at /home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:462:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/home/trongnm/Documents/apieth/node_modules/web3-eth-contract/lib/index.js:461:8)
    at Object.transfer (/home/trongnm/Documents/apieth/app/services/tokenServices.js:37:73)
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:111:48)
[2022-07-07 14:53:24] [[31merror[39m] ReferenceError: BigNumber is not defined
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:99:29)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 15:11:52] [[31merror[39m] Error: Key derivation failed - possibly wrong password
    at Accounts.decrypt (/home/trongnm/Documents/apieth/node_modules/web3-eth-accounts/lib/index.js:438:15)
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:107:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-07 15:12:03] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at transfer (/home/trongnm/Documents/apieth/app/controllers/tokenController.js:94:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-08 12:52:56] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at login (/home/happy/apieth/app/controllers/authController.js:37:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-08 13:05:22] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/happy/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/happy/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/happy/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-08 13:05:23] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/happy/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/happy/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/happy/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-08 13:05:24] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/happy/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/happy/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/happy/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-08 13:05:24] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/happy/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/happy/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/happy/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-08 13:05:25] [[31merror[39m] Error: Returned error: insufficient funds for gas * price + value
    at Object.ErrorResponse (/home/happy/apieth/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/happy/apieth/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (/home/happy/apieth/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/happy/apieth/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2022-07-08 13:39:18] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at getBalance (/home/happy/apieth/app/controllers/tokenController.js:69:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-11 09:22:37] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/happy/apieth/app/controllers/authController.js:71:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-11 09:23:33] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/happy/apieth/app/controllers/authController.js:71:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-11 09:23:40] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/happy/apieth/app/controllers/authController.js:71:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-11 09:25:44] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/happy/apieth/app/controllers/authController.js:71:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-11 09:25:50] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/happy/apieth/app/controllers/authController.js:71:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-11 09:25:51] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/happy/apieth/app/controllers/authController.js:71:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-11 09:42:48] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/happy/apieth/app/controllers/authController.js:70:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-11 14:46:26] [[31merror[39m] ReferenceError: data is not defined
    at getToken (/home/happy/apieth/app/controllers/tokenController.js:136:55)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/happy/apieth/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at /home/happy/apieth/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/happy/apieth/node_modules/express/lib/router/index.js:346:12)
    at next (/home/happy/apieth/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/happy/apieth/node_modules/express/lib/router/index.js:175:3)
    at router (/home/happy/apieth/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/happy/apieth/node_modules/express/lib/router/index.js:328:13)
    at /home/happy/apieth/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/happy/apieth/node_modules/express/lib/router/index.js:346:12)
    at next (/home/happy/apieth/node_modules/express/lib/router/index.js:280:10)
    at logger (/home/happy/apieth/node_modules/morgan/index.js:144:5)
[2022-07-11 14:46:51] [[31merror[39m] ReferenceError: data is not defined
    at getToken (/home/happy/apieth/app/controllers/tokenController.js:136:55)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/happy/apieth/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at /home/happy/apieth/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/happy/apieth/node_modules/express/lib/router/index.js:346:12)
    at next (/home/happy/apieth/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/happy/apieth/node_modules/express/lib/router/index.js:175:3)
    at router (/home/happy/apieth/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/happy/apieth/node_modules/express/lib/router/index.js:328:13)
    at /home/happy/apieth/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/happy/apieth/node_modules/express/lib/router/index.js:346:12)
    at next (/home/happy/apieth/node_modules/express/lib/router/index.js:280:10)
    at logger (/home/happy/apieth/node_modules/morgan/index.js:144:5)
[2022-07-11 15:04:41] [[31merror[39m] ReferenceError: error is not defined
    at Object.findAll (/home/happy/apieth/app/services/tokenServices.js:63:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:137:27)
[2022-07-11 15:04:43] [[31merror[39m] ReferenceError: error is not defined
    at Object.findAll (/home/happy/apieth/app/services/tokenServices.js:63:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:137:27)
[2022-07-11 15:05:13] [[31merror[39m] find all: SyntaxError: Unexpected token E in JSON at position 0
[2022-07-11 15:05:13] [[31merror[39m] SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.findAll (/home/happy/apieth/app/services/tokenServices.js:60:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:137:27)
[2022-07-11 15:05:47] [[31merror[39m] find all: SyntaxError: Unexpected token E in JSON at position 0
[2022-07-11 15:05:47] [[31merror[39m] SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.findAll (/home/happy/apieth/app/services/tokenServices.js:61:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:137:27)
[2022-07-11 16:30:19] [[31merror[39m] Mint token: TypeError: contract.methods.mint is not a function
[2022-07-11 16:30:19] [[31merror[39m] TypeError: contract.methods.mint is not a function
    at Object.tokenMint (/home/happy/apieth/app/services/tokenServices.js:57:42)
    at tokenMint (/home/happy/apieth/app/controllers/tokenController.js:170:48)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-11 16:33:57] [[31merror[39m] Mint token: TypeError: contract.methods.mint is not a function
[2022-07-11 16:33:57] [[31merror[39m] TypeError: contract.methods.mint is not a function
    at Object.tokenMint (/home/happy/apieth/app/services/tokenServices.js:57:42)
    at tokenMint (/home/happy/apieth/app/controllers/tokenController.js:170:48)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 11:29:43] [[31merror[39m] ReferenceError: ethServices is not defined
    at sendEth (/home/happy/apieth/app/controllers/ethController.js:32:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 11:30:22] [[31merror[39m] TypeError: ethServices.sendEth is not a function
    at sendEth (/home/happy/apieth/app/controllers/ethController.js:33:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 11:30:41] [[31merror[39m] Send Eth: ReferenceError: Cannot access 'data' before initialization
[2022-07-14 11:30:41] [[31merror[39m] ReferenceError: Cannot access 'data' before initialization
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:15:25)
    at sendEth (/home/happy/apieth/app/controllers/ethController.js:33:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 11:31:30] [[31merror[39m] Send Eth: ReferenceError: web3 is not defined
[2022-07-14 11:31:30] [[31merror[39m] ReferenceError: web3 is not defined
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:16:40)
    at sendEth (/home/happy/apieth/app/controllers/ethController.js:33:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 11:32:14] [[31merror[39m] Send Eth: ReferenceError: eth is not defined
[2022-07-14 11:32:14] [[31merror[39m] ReferenceError: eth is not defined
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:28:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 11:33:00] [[31merror[39m] TypeError: Cannot read property 'address' of undefined
    at callContract (/home/happy/apieth/app/blockchain/eth/ethGateWay.js:30:36)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at callContract (internal/util.js:296:12)
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:32:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 11:34:36] [[31merror[39m] TypeError: Cannot read property 'address' of undefined
    at callContract (/home/happy/apieth/app/blockchain/eth/ethGateWay.js:30:36)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at callContract (internal/util.js:296:12)
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:32:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 11:35:00] [[31merror[39m] TypeError: Cannot read property 'address' of undefined
    at callContract (/home/happy/apieth/app/blockchain/eth/ethGateWay.js:30:36)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at callContract (internal/util.js:296:12)
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:32:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 11:38:13] [[31merror[39m] Send Eth: Error: Balance of Fns insufficient
[2022-07-14 11:38:13] [[31merror[39m] Error: Balance of Fns insufficient
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:20:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 11:38:59] [[31merror[39m] Send Eth: Error: Balance of Fns insufficient
[2022-07-14 11:38:59] [[31merror[39m] Error: Balance of Fns insufficient
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:20:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 11:39:19] [[31merror[39m] Send Eth: TypeError: balanceOfFrAddress.toNumber is not a function
[2022-07-14 11:39:19] [[31merror[39m] TypeError: balanceOfFrAddress.toNumber is not a function
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:19:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 11:40:12] [[31merror[39m] Send Eth: TypeError: web3.eth.getBalance(...).toNumber is not a function
[2022-07-14 11:40:12] [[31merror[39m] TypeError: web3.eth.getBalance(...).toNumber is not a function
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:17:88)
    at sendEth (/home/happy/apieth/app/controllers/ethController.js:33:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 11:40:40] [[31merror[39m] Send Eth: TypeError: data.amounttoNumber is not a function
[2022-07-14 11:40:40] [[31merror[39m] TypeError: data.amounttoNumber is not a function
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:19:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 11:41:34] [[31merror[39m] Send Eth: Error: Balance of Fns insufficient
[2022-07-14 11:41:34] [[31merror[39m] Error: Balance of Fns insufficient
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:18:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 11:41:53] [[31merror[39m] Send Eth: Error: Balance of ETH insufficient
[2022-07-14 11:41:53] [[31merror[39m] Error: Balance of ETH insufficient
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:18:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 14:57:31] [[31merror[39m] find all: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-14 14:57:31] [[31merror[39m] SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.findAll (/home/happy/apieth/app/services/tokenServices.js:92:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:140:27)
[2022-07-14 14:58:48] [[31merror[39m] find all: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-14 14:58:48] [[31merror[39m] SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.findAll (/home/happy/apieth/app/services/tokenServices.js:92:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:140:27)
[2022-07-14 14:59:43] [[31merror[39m] find all: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-14 14:59:43] [[31merror[39m] SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.findAll (/home/happy/apieth/app/services/tokenServices.js:93:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:140:27)
[2022-07-14 15:01:32] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at create (/home/happy/apieth/app/controllers/tokenController.js:21:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 15:20:36] [[31merror[39m] Get Balance Internal Exchange: Error: Invalid protocol: 103.161.38.166:
[2022-07-14 15:20:36] [[31merror[39m] Error: Invalid protocol: 103.161.38.166:
    at Request.init (/home/happy/apieth/node_modules/request/request.js:458:31)
    at new Request (/home/happy/apieth/node_modules/request/request.js:127:8)
    at request (/home/happy/apieth/node_modules/request/index.js:53:10)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at request (internal/util.js:296:12)
    at Object.getProduct (/home/happy/apieth/app/services/thirdServices.js:26:36)
    at getToken (/home/happy/apieth/app/controllers/tokenController.js:141:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 15:21:41] [[31merror[39m] Get Balance Internal Exchange: Error: Invalid protocol: 103.161.38.166:
[2022-07-14 15:21:41] [[31merror[39m] Error: Invalid protocol: 103.161.38.166:
    at Request.init (/home/happy/apieth/node_modules/request/request.js:458:31)
    at new Request (/home/happy/apieth/node_modules/request/request.js:127:8)
    at request (/home/happy/apieth/node_modules/request/index.js:53:10)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at request (internal/util.js:296:12)
    at Object.getProduct (/home/happy/apieth/app/services/thirdServices.js:26:36)
    at getToken (/home/happy/apieth/app/controllers/tokenController.js:141:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 15:22:54] [[31merror[39m] Get Balance Internal Exchange: TypeError: Cannot read property 'data' of undefined
[2022-07-14 15:22:54] [[31merror[39m] TypeError: Cannot read property 'data' of undefined
    at Object.getProduct (/home/happy/apieth/app/services/thirdServices.js:35:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:141:29)
[2022-07-14 15:24:05] [[31merror[39m] Get Balance Internal Exchange: TypeError: Cannot read property 'data' of undefined
[2022-07-14 15:24:05] [[31merror[39m] TypeError: Cannot read property 'data' of undefined
    at Object.getProduct (/home/happy/apieth/app/services/thirdServices.js:35:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:141:29)
[2022-07-14 15:24:29] [[31merror[39m] Get Balance Internal Exchange: TypeError: Cannot read property 'data' of undefined
[2022-07-14 15:24:29] [[31merror[39m] TypeError: Cannot read property 'data' of undefined
    at Object.getProduct (/home/happy/apieth/app/services/thirdServices.js:35:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:141:29)
[2022-07-14 16:05:06] [[31merror[39m] find one token: SyntaxError: Unexpected token E in JSON at position 0
[2022-07-14 16:05:06] [[31merror[39m] SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.findOne (/home/happy/apieth/app/services/tokenServices.js:106:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getTokenById (/home/happy/apieth/app/controllers/tokenController.js:162:27)
[2022-07-14 16:05:28] [[31merror[39m] find one token: SyntaxError: Unexpected token E in JSON at position 0
[2022-07-14 16:05:28] [[31merror[39m] SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.findOne (/home/happy/apieth/app/services/tokenServices.js:107:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getTokenById (/home/happy/apieth/app/controllers/tokenController.js:162:27)
[2022-07-14 16:06:06] [[31merror[39m] ReferenceError: product is not defined
    at getTokenById (/home/happy/apieth/app/controllers/tokenController.js:164:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 16:09:21] [[31merror[39m] Internal Server Error! 
[2022-07-14 16:09:21] [[31merror[39m] Get product ReferenceError: error is not defined
[2022-07-14 16:09:21] [[31merror[39m] ReferenceError: error is not defined
    at Object.getOneProduct (/home/happy/apieth/app/services/thirdServices.js:75:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getTokenById (/home/happy/apieth/app/controllers/tokenController.js:164:29)
[2022-07-14 16:09:35] [[31merror[39m] Internal Server Error! 
[2022-07-14 16:09:35] [[31merror[39m] Get product ReferenceError: error is not defined
[2022-07-14 16:09:35] [[31merror[39m] ReferenceError: error is not defined
    at Object.getOneProduct (/home/happy/apieth/app/services/thirdServices.js:75:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getTokenById (/home/happy/apieth/app/controllers/tokenController.js:164:29)
[2022-07-14 16:34:08] [[31merror[39m] Get product ReferenceError: relateDiary is not defined
[2022-07-14 16:34:08] [[31merror[39m] ReferenceError: relateDiary is not defined
    at Object.getDiaryById (/home/happy/apieth/app/services/thirdServices.js:101:103)
    at getDiaryById (/home/happy/apieth/app/controllers/tokenController.js:191:49)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/happy/apieth/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at /home/happy/apieth/node_modules/express/lib/router/index.js:284:15
    at param (/home/happy/apieth/node_modules/express/lib/router/index.js:365:14)
    at param (/home/happy/apieth/node_modules/express/lib/router/index.js:376:14)
    at param (/home/happy/apieth/node_modules/express/lib/router/index.js:376:14)
    at param (/home/happy/apieth/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/home/happy/apieth/node_modules/express/lib/router/index.js:421:3)
    at next (/home/happy/apieth/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/happy/apieth/node_modules/express/lib/router/index.js:175:3)
    at router (/home/happy/apieth/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
[2022-07-14 16:34:28] [[31merror[39m] Get product SyntaxError: Unexpected token < in JSON at position 0
[2022-07-14 16:34:28] [[31merror[39m] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.getDiaryById (/home/happy/apieth/app/services/thirdServices.js:115:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getDiaryById (/home/happy/apieth/app/controllers/tokenController.js:191:29)
[2022-07-14 17:25:44] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/happy/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 17:32:59] [[31merror[39m] Error: Key derivation failed - possibly wrong password
    at Accounts.decrypt (/home/happy/apieth/node_modules/web3-eth-accounts/lib/index.js:438:15)
    at sendEth (/home/happy/apieth/app/controllers/ethController.js:27:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 17:33:10] [[31merror[39m] Error: Key derivation failed - possibly wrong password
    at Accounts.decrypt (/home/happy/apieth/node_modules/web3-eth-accounts/lib/index.js:438:15)
    at sendEth (/home/happy/apieth/app/controllers/ethController.js:27:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 17:33:19] [[31merror[39m] Send Eth: Error: Balance of ETH insufficient
[2022-07-14 17:33:19] [[31merror[39m] Error: Balance of ETH insufficient
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:18:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 17:33:32] [[31merror[39m] Send Eth: Error: Balance of ETH insufficient
[2022-07-14 17:33:32] [[31merror[39m] Error: Balance of ETH insufficient
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:18:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-14 18:05:56] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/happy/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 18:16:41] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at create (/home/happy/apieth/app/controllers/tokenController.js:21:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 18:40:35] [[31merror[39m] Get product TypeError: data.data.lenght is not a function
[2022-07-14 18:40:35] [[31merror[39m] TypeError: data.data.lenght is not a function
    at Object.getProduct (/home/happy/apieth/app/services/thirdServices.js:27:52)
    at getToken (/home/happy/apieth/app/controllers/tokenController.js:141:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 18:41:16] [[31merror[39m] Get product TypeError: data.data.length is not a function
[2022-07-14 18:41:16] [[31merror[39m] TypeError: data.data.length is not a function
    at Object.getProduct (/home/happy/apieth/app/services/thirdServices.js:27:52)
    at getToken (/home/happy/apieth/app/controllers/tokenController.js:141:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 18:42:35] [[31merror[39m] Get product TypeError: "data.data".length is not a function
[2022-07-14 18:42:35] [[31merror[39m] TypeError: "data.data".length is not a function
    at Object.getProduct (/home/happy/apieth/app/services/thirdServices.js:27:54)
    at getToken (/home/happy/apieth/app/controllers/tokenController.js:141:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 18:50:28] [[31merror[39m] Get product TypeError: Cannot read property 'concat' of undefined
[2022-07-14 18:50:28] [[31merror[39m] TypeError: Cannot read property 'concat' of undefined
    at /home/happy/apieth/app/services/thirdServices.js:50:36
    at Array.map (<anonymous>)
    at /home/happy/apieth/app/services/thirdServices.js:43:35
    at Array.map (<anonymous>)
    at Object.getProduct (/home/happy/apieth/app/services/thirdServices.js:42:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getToken (/home/happy/apieth/app/controllers/tokenController.js:141:29)
[2022-07-14 18:54:15] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at create (/home/happy/apieth/app/controllers/tokenController.js:21:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 18:58:24] [[31merror[39m] Get product TypeError: Cannot read property 'product_id' of null
[2022-07-14 18:58:24] [[31merror[39m] TypeError: Cannot read property 'product_id' of null
    at Object.getOneProduct (/home/happy/apieth/app/services/thirdServices.js:72:83)
    at getTokenById (/home/happy/apieth/app/controllers/tokenController.js:163:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 18:59:43] [[31merror[39m] Get product TypeError: Cannot read property 'product_id' of null
[2022-07-14 18:59:43] [[31merror[39m] TypeError: Cannot read property 'product_id' of null
    at Object.getOneProduct (/home/happy/apieth/app/services/thirdServices.js:72:83)
    at getTokenById (/home/happy/apieth/app/controllers/tokenController.js:163:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 19:00:15] [[31merror[39m] Get product TypeError: Cannot read property 'product_id' of null
[2022-07-14 19:00:15] [[31merror[39m] TypeError: Cannot read property 'product_id' of null
    at Object.getOneProduct (/home/happy/apieth/app/services/thirdServices.js:72:83)
    at getTokenById (/home/happy/apieth/app/controllers/tokenController.js:164:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 19:03:12] [[31merror[39m] Get product TypeError: Cannot read property 'product_id' of null
[2022-07-14 19:03:12] [[31merror[39m] TypeError: Cannot read property 'product_id' of null
    at Object.getOneProduct (/home/happy/apieth/app/services/thirdServices.js:72:83)
    at getTokenById (/home/happy/apieth/app/controllers/tokenController.js:164:49)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-14 19:24:27] [[31merror[39m] Send Eth: Error: Balance of ETH insufficient
[2022-07-14 19:24:27] [[31merror[39m] Error: Balance of ETH insufficient
    at Object.sendEth (/home/happy/apieth/app/services/ethServices.js:18:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendEth (/home/happy/apieth/app/controllers/ethController.js:33:28)
[2022-07-15 15:16:52] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at create (/home/happy/apieth/app/controllers/tokenController.js:21:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-18 13:51:17] [[31merror[39m] Event Transfer: Error: Returned error: query returned more than 10000 results
[2022-07-18 13:55:19] [[31merror[39m] Event Transfer: Error: Returned error: query returned more than 10,000 results spanning multiple blocks
[2022-07-18 14:13:26] [[31merror[39m] find one latest: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:13:26] [[31merror[39m] Event Transfer: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:14:23] [[31merror[39m] find one latest: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:14:23] [[31merror[39m] Event Transfer: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:14:47] [[31merror[39m] find one latest: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:14:47] [[31merror[39m] Event Transfer: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:14:56] [[31merror[39m] find one latest: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:14:56] [[31merror[39m] Event Transfer: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:15:34] [[31merror[39m] find one latest: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:15:34] [[31merror[39m] Event Transfer: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:19:36] [[31merror[39m] find one latest: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:19:36] [[31merror[39m] Event Transfer: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:21:35] [[31merror[39m] find one latest: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:21:35] [[31merror[39m] Event Transfer: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:23:41] [[31merror[39m] find one latest: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:23:41] [[31merror[39m] Event Transfer: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:24:34] [[31merror[39m] find one latest: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 14:24:34] [[31merror[39m] Event Transfer: SyntaxError: Unexpected token S in JSON at position 0
[2022-07-18 15:36:26] [[31merror[39m] Event Transfer: Error: Given input "[object Object]" is not a number.
[2022-07-18 15:37:05] [[31merror[39m] Event Transfer: Error: Given input "[object Object]" is not a number.
[2022-07-18 15:38:18] [[31merror[39m] Event Transfer: Error: Given input "[object Object]" is not a number.
[2022-07-18 16:42:57] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-18 16:49:31] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at login (/home/trongnm/Documents/apieth/app/controllers/authController.js:37:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-18 17:37:03] [[31merror[39m] Event Transfer: ReferenceError: error is not defined
[2022-07-18 17:38:01] [[31merror[39m] Event Transfer: ReferenceError: result is not defined
[2022-07-18 17:38:20] [[31merror[39m] Event Transfer: TypeError: findEthHistory.map is not a function
[2022-07-18 17:39:02] [[31merror[39m] Event Transfer: ReferenceError: error is not defined
[2022-07-18 17:39:23] [[31merror[39m] Event Transfer: ReferenceError: result is not defined
[2022-07-18 17:39:43] [[31merror[39m] Event Transfer: ReferenceError: result is not defined
[2022-07-18 17:41:52] [[31merror[39m] Event Transfer: TypeError: findEthHistory.map is not a function
[2022-07-18 17:47:53] [[31merror[39m] Event Transfer: TypeError: findEthHistory.map is not a function
[2022-07-18 17:57:00] [[31merror[39m] Event Transfer: TypeError: ethEntities.update is not a function
[2022-07-22 10:54:58] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-22 10:55:07] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-22 10:55:08] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-22 10:55:09] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-22 10:55:09] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-22 10:55:10] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-22 10:55:10] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-22 10:55:11] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-22 10:55:12] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-22 10:55:12] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at register (/home/trongnm/Documents/apieth/app/controllers/authController.js:72:31)
    at Layer.handle [as handle_request] (/home/trongnm/Documents/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/trongnm/Documents/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/trongnm/Documents/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-24 22:59:10] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at tokenPrice (/home/happy/apieth/app/controllers/tokenController.js:330:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-24 22:59:52] [[31merror[39m] Error: Validation failed, entered data is incorrect.
    at tokenPrice (/home/happy/apieth/app/controllers/tokenController.js:330:31)
    at Layer.handle [as handle_request] (/home/happy/apieth/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/happy/apieth/node_modules/express/lib/router/route.js:144:13)
    at middleware (/home/happy/apieth/node_modules/express-validator/src/middlewares/check.js:16:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-07-24 23:00:34] [[31merror[39m] price token: SyntaxError: Unexpected token x in JSON at position 1
[2022-07-24 23:00:34] [[31merror[39m] SyntaxError: Unexpected token x in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.tokenPrice (/home/happy/apieth/app/services/tokenServices.js:140:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async tokenPrice (/home/happy/apieth/app/controllers/tokenController.js:348:28)
[2022-07-24 23:02:10] [[31merror[39m] price token: SyntaxError: Unexpected token x in JSON at position 1
[2022-07-24 23:02:10] [[31merror[39m] SyntaxError: Unexpected token x in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.tokenPrice (/home/happy/apieth/app/services/tokenServices.js:141:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async tokenPrice (/home/happy/apieth/app/controllers/tokenController.js:348:28)
